# Site settings
title: Tom Wan
twitter_username: chibbluffy
name: Tom Wan

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
 - title: GitHub
   url: https://github.com/chibbluffy
 - title: LinkedIn
   url: https://www.linkedin.com/in/xianywan/

#Any buzzword skills you want to include
skills:
 - Java
 - JavaScript
 - SQL
 - REST
 - Machine learning
 

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Student Co-op/Intern
   start: 2017
   end: 2019
   employer: Adtran Inc.
   description: Networking company which deals with telecommunications equipment and software. Transitioning from a hardware based company to a software/cloud solution based company.  <a href="https://www.adtran.com" taget="_blank">Adtran</a>
 - title: Student Worker/Graduate Student Assistant
   start: 2015
   end: Ongoing
   employer: University of Alabama IT Service Desk
   description: IT department for the entirety of the University of Alabama. Serves students, faculty, and staff to troubleshoot and assist with all technical and account needs. 

#Education is required
education:
 - level: Bachelor of Science (B.S.)
   date: 2019
   subject: Computer Science
   school: University of Alabama
 - level: Masters of Business Administration (MBA)
   date: 2020
   subject: Business Analytics
   school: University of Alabama


#List of interesting Github repo/projects to include - optional
github:
 - chibbluffy/chibbluffy.github.io
 - chibbluffy/

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/7113140/chibbluffy
   flairimageurl: https://stackoverflow.com/users/flair/7113140.png

intro: |
  I am an engineer with 2-5 years experience working in technology. 
  
  
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Python</strong>: I use python the most, and I love it. These days, I use it mostly to create scripts/macros to make things easier for myself. 
   <></>: 
   I've worked with a lot of different languages and technologies from class, work, hackathons and side-projects. I'm not limited to what I currently know. 
   
   
   
   
